net use l: /d 2>nul
SET RELEASE_ZIP_FILE_SOURCE_RELATIVE_PATH=l:\mpt2sas-release.tar.gz
SET RELEASE_ZIP_FILE_TARGET_RELATIVE_PATH=..\..\sas2_rel\mpt2sas_rhel5_rel\mpt2sas-release.tar.gz
net use l: \\172.21.64.147\builds
attrib -R %RELEASE_ZIP_FILE_TARGET_RELATIVE_PATH%
del /q %RELEASE_ZIP_FILE_TARGET_RELATIVE_PATH%
copy /y %RELEASE_ZIP_FILE_SOURCE_RELATIVE_PATH% %RELEASE_ZIP_FILE_TARGET_RELATIVE_PATH%

