obj-$(CONFIG_SYNOBIOS_109_MV) += ds109-synobios.o
obj-$(CONFIG_SYNOBIOS_209_MV) += ds209-synobios.o
obj-$(CONFIG_SYNOBIOS_409slim_MV) += ds409slim-synobios.o
obj-$(CONFIG_SYNOBIOS_409_MV) += ds409-synobios.o
obj-$(CONFIG_SYNOBIOS_RS409_MV) += rs409-synobios.o
obj-$(CONFIG_SYNOBIOS_110j_MV) += ds110j-synobios.o
obj-$(CONFIG_SYNOBIOS_210j_MV) += ds210j-synobios.o
obj-$(CONFIG_SYNOBIOS_410j_MV) += ds410j-synobios.o
obj-$(CONFIG_SYNOBIOS_110_MV) += ds110-synobios.o

common-obj = ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o

ds109-synobios-objs = ds109.o $(common-obj)
ds209-synobios-objs = ds209.o $(common-obj)
ds409slim-synobios-objs = ds409slim.o $(common-obj)
ds409-synobios-objs = ds409.o $(common-obj)
rs409-synobios-objs = rs409.o $(common-obj)
ds110j-synobios-objs = ds110j.o $(common-obj)
ds210j-synobios-objs = ds210j.o $(common-obj)
ds410j-synobios-objs = ds410j.o $(common-obj)
ds110-synobios-objs = ds110.o $(common-obj)

#ds109-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds209-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds409-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds409slim-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#rs409-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds110j-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds210j-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds410j-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
#ds110-synobios-objs += ../synobios.o ../i2c/i2c-mv.o ../rtc/rtc-mv-ricoh.o ../rtc/rtc-mv-seiko.o ../mapping.o mv6281_common.o
