# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ION_REALTEK) +=	ion.o ion-ioctl.o ion_heap.o
obj-$(CONFIG_ION_SYSTEM_HEAP_REALTEK) += ion_system_heap.o ion_page_pool.o
obj-$(CONFIG_ION_CARVEOUT_HEAP_REALTEK) += ion_carveout_heap.o
obj-$(CONFIG_ION_CHUNK_HEAP_REALTEK) += ion_chunk_heap.o
obj-$(CONFIG_ION_CMA_HEAP_REALTEK) += ion_cma_heap.o

obj-$(CONFIG_ION_RTK_DHC_HEAP) += rtk/
