#!/bin/bash
# Copyright (c) 2000-2020 Synology Inc. All rights reserved.
# vim:ft=sh

config_debug_mode()
{
    local _cfg=
    local _enabled="
        CONFIG_DEBUG_FS
        CONFIG_PERF_EVENTS

        CONFIG_DEBUG_INFO
        CONFIG_FRAME_POINTER

        CONFIG_DEBUG_SPINLOCK
        CONFIG_DEBUG_MUTEXES
        CONFIG_DEBUG_ATOMIC_SLEEP

        CONFIG_FTRACE
        CONFIG_BRANCH_PROFILE_NONE
        CONFIG_FUNCTION_TRACER
        CONFIG_FTRACE_SYSCALLS
        CONFIG_IRQSOFF_TRACER
        CONFIG_PREEMPT_TRACER
        CONFIG_SCHED_TRACER
        CONFIG_BLK_DEV_IO_TRACE
        CONFIG_STACK_TRACER
        CONFIG_UPROBE_EVENT
        CONFIG_FUNCTION_PROFILER

        CONFIG_KPROBES
        #CONFIG_BPF_SYSCALL
    "
    local _disabled="
    "

    for _cfg in $_enabled; do
        INFO "Enable $_cfg"
        ./scripts/config --enable $_cfg
    done

    for _cfg in $_disabled; do
        INFO "Disable $_cfg"
        ./scripts/config --disable $_cfg
    done
}
