#!/bin/bash
# Copyright (c) 2000-2016 Synology Inc. All rights reserved.

skip=0

ModCrypto=" \
	${KernelDir}/crypto/aes_generic.ko \
	${KernelDir}/crypto/ansi_cprng.ko \
	${KernelDir}/crypto/ecb.ko \
	${KernelDir}/crypto/sha1_generic.ko \
	${KernelDir}/crypto/sha256_generic.ko \
	${KernelDir}/crypto/sha512_generic.ko \
	"
ModFS=" \
	${KernelDir}/fs/fat/fat.ko \
	${KernelDir}/fs/fat/vfat.ko \
	${KernelDir}/fs/hfsplus/hfsplus.ko \
	"
ModEncFS=" \
	${KernelDir}/fs/ecryptfs/ecryptfs.ko \
	"
ModFUSE=" \
	${KernelDir}/fs/fuse/fuse.ko \
	"
ModISOFS=" \
	${KernelDir}/drivers/block/loop.ko \
	${KernelDir}/fs/isofs/isofs.ko \
	${KernelDir}/fs/udf/udf.ko \
	${KernelDir}/lib/crc-itu-t.ko \
	"
Mod2Lan=" \
	${KernelDir}/drivers/net/bonding/bonding.ko \
	"
ModAppleTalk=" \
	${KernelDir}/net/802/psnap.ko \
	${KernelDir}/net/appletalk/appletalk.ko \
	${KernelDir}/net/llc/llc.ko \
	"
ModFirewall=" \
	${KernelDir}/net/ipv4/netfilter/ip_tables.ko \
	${KernelDir}/net/ipv4/netfilter/ipt_REDIRECT.ko \
	${KernelDir}/net/ipv4/netfilter/iptable_filter.ko \
	${KernelDir}/net/ipv4/netfilter/iptable_nat.ko \
	${KernelDir}/net/ipv4/netfilter/nf_conntrack_ipv4.ko \
	${KernelDir}/net/ipv4/netfilter/nf_defrag_ipv4.ko \
	${KernelDir}/net/ipv4/netfilter/nf_nat.ko \
	${KernelDir}/net/netfilter/nf_conntrack.ko \
	${KernelDir}/net/netfilter/x_tables.ko \
	${KernelDir}/net/netfilter/xt_multiport.ko \
	${KernelDir}/net/netfilter/xt_state.ko \
	${KernelDir}/net/netfilter/xt_tcpudp.ko \
	${KernelDir}/net/ipv4/netfilter/ipt_LOG.ko \
	${KernelDir}/net/netfilter/xt_limit.ko \
	${KernelDir}/net/netfilter/xt_iprange.ko \
	${KernelDir}/net/netfilter/xt_TCPMSS.ko \
	"
ModIPv6FW=" \
	${KernelDir}/net/ipv6/netfilter/ip6_tables.ko \
	${KernelDir}/net/ipv6/netfilter/ip6table_filter.ko \
	${KernelDir}/net/ipv6/netfilter/nf_conntrack_ipv6.ko \
	${KernelDir}/net/ipv6/netfilter/ip6t_LOG.ko \
	"
ModIPv6=" \
	${KernelDir}/net/ipv6/ipv6.ko \
	"
ModeIPv6Tun=" \
	${KernelDir}/net/ipv4/tunnel4.ko \
	${KernelDir}/net/ipv6/sit.ko \
	"
ModNFQ=" \
	${KernelDir}/net/netfilter/nfnetlink.ko \
	${KernelDir}/net/netfilter/nfnetlink_queue.ko \
	${KernelDir}/net/netfilter/xt_NFQUEUE.ko \
	"
ModPPP=" \
	${KernelDir}/drivers/net/ppp_async.ko \
	${KernelDir}/drivers/net/ppp_generic.ko \
	${KernelDir}/drivers/net/ppp_synctty.ko \
	${KernelDir}/drivers/net/pppox.ko \
	${KernelDir}/drivers/net/pppoe.ko \
	${KernelDir}/drivers/net/slhc.ko \
	${KernelDir}/drivers/char/n_hdlc.ko \
	${KernelDir}/drivers/net/bsd_comp.ko
	${KernelDir}/drivers/net/ppp_deflate.ko
	${KernelDir}/drivers/net/ppp_mppe.ko
	${KernelDir}/drivers/net/pppol2tp.ko
	${KernelDir}/lib/crc-ccitt.ko \
	"
ModTunnel=" \
	${KernelDir}/drivers/net/tun.ko \
	"
ModISCSI=" \
	${KernelDir}/crypto/crc32c.ko \
	${KernelDir}/lib/libcrc32c.ko \
	"
ModNFSD=" \
	${KernelDir}/fs/exportfs/exportfs.ko \
	${KernelDir}/fs/nfsd/nfsd.ko \
	"
ModCIFS=" \
	${KernelDir}/fs/cifs/cifs.ko \
	"
ModQuota=" \
	${KernelDir}/fs/quota/quota_tree.ko \
	${KernelDir}/fs/quota/quota_v2.ko \
	"
ModSCSI=" \
	${KernelDir}/drivers/scsi/sg.ko \
	"
ModSnapshot=" \
	${KernelDir}/drivers/md/dm-snapshot.ko \
	"
ModSound=" \
	${KernelDir}/sound/soundcore.ko \
	"
ModUSBLP=" \
	${KernelDir}/drivers/usb/class/usblp.ko \
	"
ModUSB=" \
	${KernelDir}/drivers/hid/hid.ko \
	${KernelDir}/drivers/hid/usbhid/usbhid.ko \
	${ModUSBLP} \
	${KernelDir}/drivers/usb/core/usbcore.ko \
	${KernelDir}/drivers/usb/host/ehci-hcd.ko \
	${KernelDir}/drivers/usb/storage/usb-storage.ko  \
	"
ModUSBIP=" \
	${KernelDir}/drivers/staging/usbip/usbip.ko \
	${KernelDir}/drivers/staging/usbip/usbip_common_mod.ko \
	"
ModUSBWimax=" \
	${KernelDir}/drivers/net/mii.ko \
	${KernelDir}/drivers/net/usb/usbnet.ko \
	"
ModCPUFreq=" \
	${KernelDir}/drivers/cpufreq/freq_table.ko \
	${KernelDir}/drivers/cpufreq/cpufreq_stats.ko \
	"
ModBridge=" \
	${KernelDir}/net/bridge/bridge.ko \
	${KernelDir}/net/802/stp.ko \
	"
ModDrbd=" \
	${KernelDir}/drivers/connector/cn.ko \
	${KernelDir}/crypto/hmac.ko \
	${KernelDir}/lib/libcrc32c.ko \
	"
ModTC=" \
	${KernelDir}/net/sched/sch_htb.ko \
	${KernelDir}/net/sched/sch_sfq.ko \
	${KernelDir}/net/sched/cls_fw.ko \
	${KernelDir}/net/sched/sch_netem.ko \
	${KernelDir}/net/netfilter/xt_MARK.ko \
	${KernelDir}/net/ipv4/netfilter/iptable_mangle.ko \
	${KernelDir}/net/ipv6/netfilter/ip6table_mangle.ko \
	${KernelDir}/net/sched/cls_u32.ko \
	"
ModFwSecurity=" \
	${KernelDir}/net/netfilter/nf_conntrack_proto_gre.ko \
	${KernelDir}/net/ipv4/netfilter/nf_nat_proto_gre.ko \
	${KernelDir}/net/netfilter/nf_conntrack_pptp.ko \
	${KernelDir}/net/ipv4/netfilter/nf_nat_pptp.ko \
	"
ModVlan=" \
	${KernelDir}/net/8021q/8021q.ko \
	"
ModRfkill=" \
	${KernelDir}/net/rfkill/rfkill.ko \
	"
ModIPsec=" \
	${KernelDir}/crypto/deflate.ko \
	${KernelDir}/net/ipv4/ah4.ko \
	${KernelDir}/net/ipv4/esp4.ko \
	${KernelDir}/net/ipv4/ipcomp.ko \
	${KernelDir}/net/ipv4/xfrm4_tunnel.ko \
	${KernelDir}/net/ipv4/xfrm4_mode_beet.ko \
	${KernelDir}/net/ipv4/tunnel4.ko \
	${KernelDir}/net/ipv4/xfrm4_mode_transport.ko \
	${KernelDir}/net/ipv4/xfrm4_mode_tunnel.ko \
	${KernelDir}/net/xfrm/xfrm_user.ko \
	${KernelDir}/net/xfrm/xfrm_ipcomp.ko \
	${KernelDir}/net/ipv6/ah6.ko \
	${KernelDir}/net/ipv6/esp6.ko \
	${KernelDir}/net/ipv6/ipcomp6.ko \
	${KernelDir}/net/ipv6/xfrm6_tunnel.ko \
	${KernelDir}/net/ipv6/tunnel6.ko \
	${KernelDir}/net/ipv6/xfrm6_mode_transport.ko \
	${KernelDir}/net/ipv6/xfrm6_mode_tunnel.ko \
	${KernelDir}/net/ipv6/xfrm6_mode_beet.ko \
	"

ModuleList=" \
	${ModCrypto} \
	${ModFS} \
	${ModEncFS} \
	${ModFUSE} \
	${ModISOFS} \
	${Mod2Lan} \
	${ModAppleTalk} \
	${ModFirewall} \
	${ModIPv6FW} \
	${ModIPv6} \
	${ModPPP} \
	${ModTunnel} \
	${ModISCSI} \
	${ModNFSD} \
	${ModCIFS} \
	${ModQuota} \
	${ModSCSI} \
	${ModSnapshot} \
	${ModSound} \
	${ModUSB} \
	${ModUSBIP} \
	${ModUSBWimax} \
	${ModDrbd} \
	"
##################################################
ModMvCesa=" \
	${KernelDir}/arch/arm/plat-feroceon/mv_drivers_lsp/mv_cesa/cesa_dev.ko \
	${KernelDir}/arch/arm/plat-feroceon/mv_drivers_lsp/mv_cesa/cesa_ocf_drv.ko \
	"
ModTalitos=" \
	${KernelDir}/crypto/authenc.ko \
	${KernelDir}/drivers/char/hw_random/rng-core.ko \
	${KernelDir}/drivers/crypto/talitos.ko \
	"
ModOCF_20100325=" \
	${KernelDir}/crypto/ocf_20100325/cryptodev.ko \
	${KernelDir}/crypto/ocf_20100325/cryptosoft.ko \
	${KernelDir}/crypto/ocf_20100325/ocf.ko \
	"
ModRaid=" \
	${KernelDir}/drivers/md/dm-mod.ko \
	${KernelDir}/drivers/md/linear.ko \
	${KernelDir}/drivers/md/raid0.ko \
	${KernelDir}/drivers/md/raid10.ko \
	${KernelDir}/drivers/md/raid456.ko \
	${KernelDir}/drivers/md/raid6_pq.ko \
	${KernelDir}/crypto/async_tx/async_tx.ko \
	${KernelDir}/crypto/async_tx/async_memcpy.ko \
	${KernelDir}/crypto/async_tx/async_xor.ko \
	${KernelDir}/crypto/async_tx/async_pq.ko \
	${KernelDir}/crypto/async_tx/async_raid6_recov.ko \
	${KernelDir}/crypto/xor.ko \
	"
ModUSBModem=" \
	${KernelDir}/drivers/usb/serial/usb_wwan.ko \
	${KernelDir}/drivers/usb/serial/option.ko \
	${KernelDir}/drivers/usb/class/cdc-acm.ko \
	${KernelDir}/drivers/usb/serial/sierra.ko \
	"

##################################################

ModUSBserial=" \
	${KernelDir}/drivers/usb/serial/usbserial.ko \
	${KernelDir}/drivers/usb/serial/ftdi_sio.ko \
	"

case "$BUILD_TARGET" in
	MARVELL_88F6281)
		ModuleList="${ModuleList} ${ModMvCesa}"
		ModuleList="${ModuleList} ${ModOCF_20100325}"
		ModuleList="${ModuleList} ${KernelDir}/net/ipv4/netfilter/ipt_MASQUERADE.ko"
		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
		ModuleList="${ModuleList} ${KernelDir}/crypto/arc4.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/net/sky2.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ohci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/xhci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/etxhci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/class/cdc-acm.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/leds/led-class.ko"
		ModuleList="${ModuleList} ${ModCPUFreq} ${KernelDir}/arch/arm/mach-feroceon-kw/cpufreq.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/cpufreq/cpufreq_performance.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/cpufreq/cpufreq_powersave.ko"
		ModuleList="${ModuleList} ${ModDrbd}"
		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
		ModuleList="${ModuleList} ${ModVlan}"
		ModuleList="${ModuleList} ${KernelDir}/drivers/i2c/i2c-core.ko"
		ModuleList="${ModuleList} ${ModRfkill}"
		ModuleList="${ModuleList} ${ModUSBserial}"
		ModuleList="${ModuleList} ${KernelDir}/crypto/authenc.ko"
		ModuleList="${ModuleList} ${ModIPsec}"
		ModuleList="${ModuleList} ${ModUSBModem}"
		ModuleList="${ModuleList} ${KernelDir}/net/netfilter/xt_mac.ko"
		ModuleList="${ModuleList} ${ModeIPv6Tun}"
		ModuleList="${ModuleList} ${ModNFQ}"

		;;
	PPC_853X)
		ModuleList="${ModuleList} ${ModTalitos}"
		ModuleList="${ModuleList} ${ModOCF_20100325}"
		ModuleList="${ModuleList} ${ModRaid}"
		ModuleList="${ModuleList} ${KernelDir}/net/ipv4/netfilter/ipt_MASQUERADE.ko"
		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
		ModuleList="${ModuleList} ${KernelDir}/crypto/arc4.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/input/input-core.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/net/skge.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ohci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/class/cdc-acm.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/leds/led-class.ko"
		ModuleList="${ModuleList} ${ModCPUFreq}"
		ModuleList="${ModuleList} ${ModDrbd}"
		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
		ModuleList="${ModuleList} ${ModVlan}"
		ModuleList="${ModuleList} ${KernelDir}/drivers/i2c/i2c-core.ko ${KernelDir}/drivers/of/of_i2c.ko ${KernelDir}/drivers/i2c/busses/i2c-mpc.ko"
		ModuleList="${ModuleList} ${ModUSBserial}"
		ModuleList="${ModuleList} ${ModIPsec}"
		ModuleList="${ModuleList} ${ModUSBModem}"
		ModuleList="${ModuleList} ${KernelDir}/net/netfilter/xt_mac.ko"
		ModuleList="${ModuleList} ${ModeIPv6Tun}"

		;;
	PPC_QORIQ)
		ModuleList="${ModuleList} ${ModTalitos}"
		ModuleList="${ModuleList} ${ModOCF_20100325}"
		ModuleList="${ModuleList} ${KernelDir}/drivers/leds/led-class.ko"
		ModuleList="${ModuleList} ${KernelDir}/net/ipv4/netfilter/ipt_MASQUERADE.ko"
		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
		ModuleList="${ModuleList} ${KernelDir}/crypto/arc4.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/input/input-core.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ohci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/xhci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/etxhci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ehci-hcd.ko"
		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/class/cdc-acm.ko"
		ModuleList="${ModuleList} ${ModDrbd}"
		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
		ModuleList="${ModuleList} ${ModVlan}"
		ModuleList="${ModuleList} ${ModUSBserial}"
		ModuleList="${ModuleList} ${ModIPsec}"
		ModuleList="${ModuleList} ${ModUSBModem}"
		ModuleList="${ModuleList} ${KernelDir}/net/netfilter/xt_mac.ko"
		ModuleList="${ModuleList} ${ModeIPv6Tun}"
		ModuleList="${ModuleList} ${ModNFQ}"

		;;
	*)
		SkipThisProject
		return
		;;
esac

mkdir -p ${DebDevBuild}/image/modules;
for EACHFILE in $ModuleList;
do
	if [ -f "$EACHFILE" ]; then
		cp -f ${EACHFILE} ${DebDevBuild}/image/modules/
		FN=`basename ${EACHFILE}`
		echo "${STRIP} -d ${DebDevBuild}/image/modules/$FN"
		${STRIP} -d ${DebDevBuild}/image/modules/$FN
		ls -l $EACHFILE
	else
		echo "Error! file $EACHFILE does not existed!"
	fi
done


case ${BUILD_TARGET} in
MARVELL_88F6281)
	ZIMAGE="${KernelDir}/arch/arm/boot/uImage"
	;;
PPC_853X)
	ZIMAGE="${KernelDir}/arch/powerpc/boot/uImage"
	;;
PPC_QORIQ)
	ZIMAGE="${KernelDir}/arch/powerpc/boot/uImage"
	;;
*)
	skip=1
	;;
esac

KernelDirBase=`basename $KernelDir`
CurDir=`pwd`
CurDirBase=`basename $CurDir`
if [ "$KernelDirBase" != "$CurDirBase" ]; then
	skip=1
fi

if [ $skip -eq 1 ]; then
	SkipThisProject
	return
fi

if [ -r "$ZIMAGE" ]; then
	cp -fv $ZIMAGE ${DebDevBuild}/image/zImage
else
	echo "$ZIMAGE does not exist...."
	exit 1
fi

SystemMap="${KernelDir}/System.map"
VmLinux="${KernelDir}/vmlinux"

mkdir -p ${DebDevBuild}/image/synodebug

if [ -r "$SystemMap" ]; then
	cp -fv $SystemMap ${DebDevBuild}/image/synodebug/
fi
if [ -r "$VmLinux" ]; then
	cp -fv $VmLinux ${DebDevBuild}/image/synodebug/
	gzip -f9 ${DebDevBuild}/image/synodebug/vmlinux
fi

# shellcheck source=/dev/null
source "$ScriptsDir/include/kernel-devel"

install -Dm644 "include/linux/syno_user.h" "$WRKDIR/include/linux/syno_user.h"
install -Dm644 "include/linux/syno_debug.h" "$WRKDIR/include/linux/syno_debug.h"

# for `kmsynoacl'
install -Dm644 "include/linux/syno_acl_xattr_ds.h" "$WRKDIR/include/linux/syno_acl_xattr_ds.h"

install -Dm644 "crypto/ocf_20100325/cryptodev.h" "$WRKDIR/include/crypto/cryptodev.h"
