#!/bin/bash

if [ -e "${KernelDir}/lib/synolib/jmb585_update_spi.ko" ]; then
	install -Dm644 ${KernelDir}/lib/synolib/jmb585_update_spi.ko  ${TmpInstDir}/lib/modules/jmb585_update_spi.ko
fi
if [ -e "${KernelDir}/lib/synolib/asm116xfwdl/asm116xfwdl.ko" ]; then
	install -Dm644 ${KernelDir}/lib/synolib/asm116xfwdl/asm116xfwdl.ko  ${TmpInstDir}/lib/modules/asm116xfwdl.ko
fi

