#include <linux/synobios.h>

#define CPLD_FAN_SPEED_0		0x0
#define CPLD_FAN_SPEED_1		0x1
#define CPLD_FAN_SPEED_2		0x2
#define CPLD_FAN_SPEED_3		0x3
#define CPLD_FAN_SPEED_4		0x4
#define CPLD_FAN_SPEED_5		0x5
#define CPLD_FAN_SPEED_6		0x6
#define CPLD_FAN_SPEED_7		0x7

#define FAN_ACTIVATION_SPEED    CPLD_FAN_SPEED_6
#define FAN_ACTIVATION_DURATION 500 

#define MODULE_T_DECLARE(FAN_T,				\
						 RAID_T,			\
						 LED_T,				\
						 THERMAL_T,			\
						 FANCTRL_T,			\
						 AUTO_POWERON_T,	\
						 DUAL_POWER_T,		\
						 USBCOPY_T,			\
						 FAN_NUMBER_T,		\
						 EBOX_TYPE,			\
						 POWER_IN_SEQ,		\
						 RTC_TYPE,			\
						 CPUTMP_T)			\
				   							\
		{										\
			fan_type:			FAN_T,			\
			raid_type:			RAID_T,			\
			led_type:			LED_T,			\
			thermal_type:		THERMAL_T,		\
			fanctrl_type:		FANCTRL_T,		\
			auto_poweron_type:	AUTO_POWERON_T,	\
			dual_power_type:	DUAL_POWER_T,	\
			usbcopy_type:		USBCOPY_T,		\
			fan_number:			FAN_NUMBER_T,	\
			ebox_type:			EBOX_TYPE,		\
			pis_type:			POWER_IN_SEQ,	\
			rtc_type:			RTC_TYPE,		\
			cputmp_type:		CPUTMP_T		\
		}

#define	MODULE_T_CS406e		MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_CS406		MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS406		MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_3, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107e		MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107v1	MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107v2	MODULE_T_DECLARE(FAN_MICROP_ALERT_FIRM,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107v3	MODULE_T_DECLARE(FAN_MICROP_ALERT_SOFT,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107pv1	MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107pv2	MODULE_T_DECLARE(FAN_MICROP_ALERT_FIRM,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS107pv3	MODULE_T_DECLARE(FAN_MICROP_ALERT_SOFT,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS207		MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS207p		MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_CS407e		MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_CS407		MODULE_T_DECLARE(FAN_CPLD_SPEED_2LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_NO,      POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS108jv1	MODULE_T_DECLARE(FAN_MICROP_ALERT_FIRM,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS108jv2	MODULE_T_DECLARE(FAN_MICROP_ALERT_SOFT,           RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_NO,      AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS408		MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS408		MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_3, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS408rp	MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_DUAL,    USBCOPY_NO,      FAN_NUMBER_4, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS508		MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_ON,      LED_DISKS_ALARM, THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_2, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS109j		MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS109p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_OFF,     LED_DISK_ESATA,  THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS110p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_OFF,     LED_DISK_ESATA,  THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS209j		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_NOT_SUPPORT, POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS209p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS209pII	MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS409p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_2, EBOX_SUPPORT,     POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS409p		MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_3, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS409rpp	MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_DUAL,    USBCOPY_NO,      FAN_NUMBER_4, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS509p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS_ALARM, THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_2, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS109		MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS209		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS409slim	MODULE_T_DECLARE(FAN_MULTI_ALWAYS,              RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS409		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS409v1	MODULE_T_DECLARE(FAN_CPLD_SPEED_1LEVEL,           RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_RS409v2	MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS410j		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS410		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_NO,      FAN_NUMBER_2, EBOX_SUPPORT,     POWER_IN_SEQ_4,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS210jv1	MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS210jv2	MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS210jv3	MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_ON,      LED_DISKS,       THERMAL_NO,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS210p		MODULE_T_DECLARE(FAN_MULTI_ALWAYS,                RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_2,   RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS110jv1	MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS110jv2	MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define	MODULE_T_DS110jv3	MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_SEIKO,   CPUTMP_NO)		 
#define	MODULE_T_DS710p		MODULE_T_DECLARE(FAN_MICROP_BANDON,               RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,      POWER_IN_SEQ_2,   RTC_BANDON,  CPUTMP_YES)		 
#define	MODULE_T_DS1010p	MODULE_T_DECLARE(FAN_MICROP_BANDON,               RAID_ON,      LED_DISKS_ALARM,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,  POWER_SINGLE,  USBCOPY_NO,     FAN_NUMBER_1, EBOX_SUPPORT,    POWER_IN_SEQ_OFF, RTC_BANDON,  CPUTMP_YES)		 
#define	MODULE_T_DS110		MODULE_T_DECLARE(FAN_MULTI_EXCEPT_SLEEP,          RAID_OFF,     LED_DISK_ESATA,  THERMAL_NO,      FANCTRL_YES,     AUTO_POWERON_YES,     POWER_SINGLE,  USBCOPY_YES,     FAN_NUMBER_1, EBOX_SUPPORT,     POWER_IN_SEQ_OFF, RTC_RICOH,   CPUTMP_NO)		 
#define MODULE_T_DS410p   MODULE_T_DECLARE(FAN_MICROP_BANDON_WITH_CPUFAN,   RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,  POWER_SINGLE,  USBCOPY_NO,     FAN_NUMBER_1, EBOX_SUPPORT,    POWER_IN_SEQ_4, RTC_BANDON, CPUTMP_YES)    
#define MODULE_T_RS810p   MODULE_T_DECLARE(FAN_MICROP_BANDON_WITH_CPUFAN,   RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,  POWER_SINGLE,  USBCOPY_NO,     FAN_NUMBER_1, EBOX_SUPPORT,    POWER_IN_SEQ_OFF, RTC_BANDON, CPUTMP_YES)    
#define MODULE_T_RS810rpp   MODULE_T_DECLARE(FAN_MICROP_BANDON_WITH_CPUFAN,   RAID_ON,      LED_DISKS,       THERMAL_YES,     FANCTRL_YES,     AUTO_POWERON_YES,  POWER_DUAL,  USBCOPY_NO,     FAN_NUMBER_1, EBOX_SUPPORT,    POWER_IN_SEQ_OFF, RTC_BANDON, CPUTMP_YES)    
#define	MODULE_T_UNKNOWN	MODULE_T_DECLARE(FAN_UNKNOWN,                     RAID_UNKNOWN, LED_UNKNOWN,     THERMAL_UNKNOWN, FANCTRL_UNKNOWN, AUTO_POWERON_UNKNOWN, POWER_UNKNOWN, USBCOPY_UNKNOWN, FAN_NUMBER_X, EBOX_NOT_SUPPORT, POWER_IN_SEQ_OFF, RTC_UNKNOWN, CPUTMP_UNKNOWN)	 

void module_type_set(module_t *pModule);
module_t *module_type_get(void);

#if SYNO_HAVE_KERNEL_VERSION(2,6,15)
int  GetFanNum(int *pFanNum);
#endif  
int  GetHwCapability(CAPABILITY *pCapability);
int  FanStatusMappingType1(FAN_STATUS status, FAN_SPEED speed, char *pSpeed_value);
int  FanStatusMappingType2(FAN_STATUS status, FAN_SPEED speed, char *pSpeed_value);
