#ifndef MY_ABC_HERE
#define MY_ABC_HERE
#endif
/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * Copyright (C) 2000-2021 Synology Inc.
 */
#ifndef _UAPI_LINUX_SYNO_H
#define _UAPI_LINUX_SYNO_H

/* syno_autoconf.h was generated by modified /scripts/kconfig/conf (MY_ABC_HERE) */
#ifndef __KERNEL__
#include <linux/syno_autoconf.h>
#endif

#ifndef LINUX_VERSION_CODE
#include <linux/version.h>
#endif
#define SYNO_HAVE_KERNEL_VERSION(a,b,c) (LINUX_VERSION_CODE >= KERNEL_VERSION((a),(b),(c)) )

#ifdef MY_ABC_HERE
#define SYNO_ARCHIVE_BIT
#if defined (F_CLEAR_ARCHIVE) || defined (F_SETSMB_ARCHIVE) || defined (F_SETSMB_HIDDEN) || \
    defined (F_SETSMB_SYSTEM) || defined (F_CLRSMB_ARCHIVE) || defined (F_CLRSMB_HIDDEN) || \
    defined (F_CLRSMB_SYSTEM) || defined (F_CLEAR_S3_ARCHIVE) ||               \
    defined (F_SETSMB_SPARSE) || defined (F_CLRSMB_SPARSE)
#error "Samba archive bit redefine."
#endif

#ifdef MY_ABC_HERE
#define SYNO_FS_SYNO_ACL
#if defined (F_CLRSMB_READONLY) || defined (F_SETSMB_READONLY) ||              \
    defined (F_CLRACL_INHERIT)  || defined (F_SETACL_INHERIT)  ||              \
    defined (F_CLRACL_OWNER_IS_GROUP) || defined (F_SETACL_OWNER_IS_GROUP) ||  \
    defined (F_SETACL_SUPPORT) || defined (F_SETACL_SUPPORT)
#error "ACL archive bit redefine."
#endif /* ACL archive bit redefine. */
#endif /* MY_ABC_HERE */

#define SYNO_FCNTL_BASE             513
#define F_CLEAR_ARCHIVE             (SYNO_FCNTL_BASE + 0)
#define F_SETSMB_ARCHIVE            (SYNO_FCNTL_BASE + 1)
#define F_SETSMB_HIDDEN             (SYNO_FCNTL_BASE + 2)
#define F_SETSMB_SYSTEM             (SYNO_FCNTL_BASE + 3)
#define F_CLRSMB_ARCHIVE            (SYNO_FCNTL_BASE + 4)
#define F_CLRSMB_HIDDEN             (SYNO_FCNTL_BASE + 5)
#define F_CLRSMB_SYSTEM             (SYNO_FCNTL_BASE + 6)
#define F_CLEAR_S3_ARCHIVE          (SYNO_FCNTL_BASE + 7)

#ifdef MY_ABC_HERE
#define F_CLRSMB_READONLY           (SYNO_FCNTL_BASE + 8)
#define F_SETSMB_READONLY           (SYNO_FCNTL_BASE + 9)
#define F_CLRACL_INHERIT            (SYNO_FCNTL_BASE + 10)
#define F_SETACL_INHERIT            (SYNO_FCNTL_BASE + 11)
#define F_CLRACL_HAS_ACL            (SYNO_FCNTL_BASE + 12)
#define F_SETACL_HAS_ACL            (SYNO_FCNTL_BASE + 13)
#define F_CLRACL_SUPPORT            (SYNO_FCNTL_BASE + 14)
#define F_SETACL_SUPPORT            (SYNO_FCNTL_BASE + 15)
#define F_CLRACL_OWNER_IS_GROUP     (SYNO_FCNTL_BASE + 16)
#define F_SETACL_OWNER_IS_GROUP     (SYNO_FCNTL_BASE + 17)
#define F_SETSMB_SPARSE             (SYNO_FCNTL_BASE + 18)
#define F_CLRSMB_SPARSE             (SYNO_FCNTL_BASE + 19)
#define SYNO_FCNTL_LAST             F_CLRSMB_SPARSE
#else /* MY_ABC_HERE */
#define F_SETSMB_SPARSE             (SYNO_FCNTL_BASE + 8)
#define F_CLRSMB_SPARSE             (SYNO_FCNTL_BASE + 9)
#define SYNO_FCNTL_LAST             F_CLRSMB_SPARSE
#endif /* MY_ABC_HERE */
#endif /* MY_ABC_HERE */




/**
 * Fix: DSM #103889
 * Dsc: Add notification for unsupported SFP+
 */
#if defined (MY_DEF_HERE) && !defined (__ASSEMBLER__)
typedef enum
{
	SFP_NOTIFY_UNSET 			= 0,
	SFP_NOTIFY_NOT_SUPPORT_DROP	= 1,	/* Interface might drop. ex: ixgbe */
	SFP_NOTIFY_NOT_SUPPORT_WARN = 2		/* Driver report not support but it might still work */
} SYNO_SFP_UNSUPPORTED_NOTIFY_TYPE;
#endif /* MY_DEF_HERE */


#ifdef MY_ABC_HERE
#define SD_IOCTL_IDLE 4746
#define SD_IOCTL_SUPPORT_SLEEP 4747
#endif /* MY_ABC_HERE */

#ifdef MY_DEF_HERE
#define SD_IOCTL_SASHOST_DISK_LED 4755
#endif /* MY_DEF_HERE */

/*
 * FIXME: The following legacy definitions are referred by userspace projects,
 * but do not depend on any kernel configs. They should be moved to a proper
 * project such as synoplatformconfig.
 */
#ifndef __KERNEL__
#define SYNO_EA
#endif /* __KERNEL__ */

/**
 * Dsc: USB copy support
 *      use port number 99 to indicate USBCOPY port
 */
#ifdef MY_ABC_HERE
#define USBCOPY_PORT_LOCATION 99
#endif /* MY_ABC_HERE */

#endif /* _UAPI_LINUX_SYNO_H */
