# SPDX-License-Identifier: GPL-2.0-only

dtb-$(CONFIG_ARCH_REALTEK) += rtd1293-ds418j.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-mele-v9.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-probox2-ava.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-xnano-x5.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1295-zidoo-x9s.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1296-ds418.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1395-bpi-m4.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1395-lionskin.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1619-mjolnir.dtb
ifeq ($(CONFIG_SYNO_LSP_RTD1619B), y)

dtb-$(CONFIG_ARCH_REALTEK) += rtd1319-pymparticles-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1319-rescue.dtb

dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-1gb-nas.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-2gb-spi.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-2gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-bleedingedge-4gb.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd1619b-rescue.dtb
endif # CONFIG_SYNO_LSP_RTD1619B
ifeq ($(CONFIG_SYNO_RTD1619B), y)
dtb-$(CONFIG_ARCH_REALTEK) += rtd-1619b-synology-ds223j.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd-1619b-synology-ds423.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd-1619b-synology-ds223.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd-1619b-synology-ds124.dtb
dtb-$(CONFIG_ARCH_REALTEK) += rtd-1619b-synology-mango.dtb
endif # CONFIG_SYNO_RTD1619B
