################################################################################
#
# Copyright (c) 2000-2012 Synology Inc. All rights reserved.
#
################################################################################

obj-$(CONFIG_GIANFAR) += gianfar_driver.o

gianfar_driver-objs := gianfar.o \
		gianfar_ethtool.o \
		gianfar_sysfs.o \
		gianfar_1588.o
 
obj-$(CONFIG_FSL_PQ_MDIO) += fsl_pq_mdio.o
