#
# This is a synology util lib,
#
obj-$(CONFIG_SYNO_PORT_MAPPING_V2) += syno_pciepath_dts_pattern.o syno_fdt.o
obj-$(CONFIG_SYNO_KEXEC_TEST) += syno_kexec_test.o
obj-$(CONFIG_SYNO_PCI_OPTIONAL_SLOT) += syno_check_on_opt_pci.o
obj-$(CONFIG_SYNO_PLUGIN_INTERFACE) += syno_plugin.o
obj-$(CONFIG_SYNO_BLK_DEV_WAIT_DISK_READY) += syno_disk_ready_check.o
obj-$(CONFIG_SYNO_SATA_SIGNAL_CHECK) += syno_sata_signal_check.o
obj-$(CONFIG_SYNO_SATA_SIGNAL_TEST) += syno_sata_signal_test.o
obj-$(CONFIG_SYNO_UART_TO_SPI_CONSOLE_LOG) += syno_uart2spi_logout.o
obj-$(CONFIG_SYNO_SATA_JMB585_FIRMWARE_UPDATE) += syno_jmb585_update_spi.o
obj-$(CONFIG_SYNO_SATA_ASM116X_FIRMWARE_UPDATE) += asm116xfwdl/
obj-$(CONFIG_SYNO_SATA_PWR_CTRL)+= syno_disk_pwr_ctrl.o
obj-$(CONFIG_SYNO_SCSI_DISK_SPINDOWN_PARALLELLY)+= syno_disk_wait_for_spindown.o
obj-$(CONFIG_SYNO_MD_BAD_SECTOR_AUTO_REMAP) += syno_draw_auto_remap_buffer.o
obj-$(CONFIG_SYNO_SATA_PWR_CTRL_TEST) += syno_hddpwrctl_test.o
obj-$(CONFIG_SYNO_AHCI_REG_READ_TEST) += syno_ahci_reg_read_test.o
