#
# This is a synology util lib,
#

obj-$(CONFIG_SYNO_KEXEC_TEST) += syno_kexec_test.o
obj-$(CONFIG_SYNO_DEBUG_FLAG) += syno_process_name_get.o
obj-$(CONFIG_SYNO_PLUGIN_INTERFACE) += syno_plugin.o
obj-$(CONFIG_SYNO_SATA_REMAP) += syno_remap_idx_get.o
obj-$(CONFIG_SYNO_OPTIONAL_PCI_SLOT) += syno_check_on_opt_pci.o
obj-$(CONFIG_SYNO_PCI_HOST_SATA_CACHE) += syno_shift_remap_table.o
obj-$(CONFIG_SYNO_MD_BAD_SECTOR_AUTO_REMAP) += syno_draw_auto_remap_buffer.o
obj-$(CONFIG_SYNO_WAIT_DISK_READY) += syno_disk_ready_check.o
