#
# This is a synology util lib,
#

obj-$(CONFIG_SYNO_KEXEC_TEST) += syno_kexec_test.o
obj-$(CONFIG_SYNO_DEBUG_FLAG) += syno_process_name_get.o
obj-$(CONFIG_SYNO_PLUGIN_INTERFACE) += syno_plugin.o
obj-$(CONFIG_SYNO_SATA_REMAP) += syno_remap_idx_get.o
obj-$(CONFIG_SYNO_OPTIONAL_PCI_SLOT) += syno_check_on_opt_pci.o
obj-$(CONFIG_SYNO_PCI_HOST_SATA_CACHE) += syno_shift_remap_table.o
obj-$(CONFIG_SYNO_SATA_CHECK) += syno_sata_check.o
obj-$(CONFIG_SYNO_DEVICE_ROM_UPDATE) += jmb585_update_spi.o
obj-$(CONFIG_SYNO_PORT_MAPPING_V2) += syno_pciepath_dts_pattern.o
obj-$(CONFIG_SYNO_SATA_TEST) += syno_sata_test.o
obj-$(CONFIG_SYNO_MD_BAD_SECTOR_AUTO_REMAP) += syno_draw_auto_remap_buffer.o
obj-$(CONFIG_SYNO_UART_TO_SPI_CONSOLE_LOG) += syno_uart2spi_logout.o
obj-$(CONFIG_SYNO_WAIT_DISK_READY) += syno_disk_ready_check.o
obj-$(CONFIG_SYNO_PCIEHP_FORCE) += syno_pciehp_force.o
obj-$(CONFIG_SYNO_PCIE_I2C) += syno_pcie_i2c.o
obj-$(CONFIG_SYNO_NVME_SW_ACTIVITY) += syno_nvme_index_fill.o
obj-$(CONFIG_SYNO_HDD_POWER_CONTROL_TEST) += syno_hddpwrctl_test.o
obj-$(CONFIG_SYNO_AHCI_REG_READ_TEST) += syno_ahci_reg_read_test.o
