 
#ifndef __SYNO_SCSI_H_
#define __SYNO_SCSI_H_

#ifdef SYNO_SAS_LINK_HOTPLUG_UEVENT
#define SZK_SAS_LINK_HOTPLUG_UEVENT "SYNO_SAS_LINK_HOTPLUG_UEVENT"
#define SZV_SAS_PHY_ADD "PHY_ADD"
#define SZV_SAS_PHY_REMOVE "PHY_REMOVE"
#endif  

#endif  
