obj-$(CONFIG_SYNOBIOS_pineview_X86) += pineview-synobios.o

pineview-synobios-objs = ../synobios.o ds410+.o ds710+.o ds1010+.o rs810+.o rs810rp+.o ../mapping.o ../rtc/localtime.o ../rtc/rtc-bandon.o bandon_common.o bandon_util.o

