# SPDX-License-Identifier: GPL-2.0
obj-y            += rtk_gpc.o
obj-y            += rtk_pd.o
obj-y            += rtk_sram.o rtk_iso.o
obj-$(CONFIG_PM) += rtk_pd-pm.o

obj-$(CONFIG_PD_RTD1295) += rtk_pd-rtd1295.o
obj-$(CONFIG_PD_RTD1395) += rtk_pd-rtd1395.o
obj-$(CONFIG_PD_RTD1619) += rtk_pd-rtd1619.o
obj-$(CONFIG_PD_RTD1619B) += rtk_pd-rtd1619b.o
